# Generated by Django 5.1.7 on 2025-06-29 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('session_type', models.CharField(choices=[('1v1', '1-on-1'), ('group', 'Group')], default='1v1', max_length=20)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('repeat_option', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, choices=[('1-5', 'Grade 1-5'), ('6-10', 'Grade 6-10'), ('11-12', 'Grade 11-12'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=50)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_hour', 'Per Hour'), ('per_booking', 'Per Booking')], default='per_booking', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cancellation_policy', models.CharField(blank=True, max_length=200)),
                ('materials_provided', models.BooleanField(default=False)),
                ('booking_deadline_minutes', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='bookings.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
